#You can eidt the color scheme in source/css/_base/variable.styl

photo: https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAJ6AAAAJGY4ZWYzNzU3LTUzZWItNDE0YS04OWQ5LWQ4ZTZjMTlkMTYxZg.jpg

email: vipinsthename@gmail.com
twitter: 
facebook: 
googleplus: 
github: vipinsthename
pinterest: 
linkedin: vipinsthename
instagram: 
zhihu: 
weibo: 
renren: 


addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

#
bighomepage: true

#Use cdnjs' CDN
usecdn: false

google_analytics: UA-44033164-1
rss: /atom.xml

forvirgo: true
